export interface OnlineCharacter {
  charname: string;
  nameflags: number;
  pos_zone: number;
  gmlevel: number;
  ls1name: string;
  ls2name: string;
  ls1color: number | string;
  ls2color: number | string;
  ls1rank: number;
  ls2rank: number;
  mjob: number;
  sjob: number;
  mlvl: number;
  slvl: number;
  mentor: number;
  charid: number;
  unlocked: number;
  genkai: number;
  war: number;
  mnk: number;
  whm: number;
  blm: number;
  rdm: number;
  thf: number;
  pld: number;
  drk: number;
  bst: number;
  brd: number;
  rng: number;
  sam: number;
  nin: number;
  drg: number;
  smn: number;
  blu: number;
  cor: number;
  pup: number;
  dnc: number;
  sch: number;
  geo: number;
  run: number;
  zonename: string;
  ishidden: number;
}
